language: en-US
early_access: true
reviews:
    high_level_summary: false
    review_status: false
    poem: false
    changed_files_summary: false
    abort_on_close: true
    instructions: >-
        - Read and follow the code review guide when doing a review: https://github.com/dimagi/open-source/blob/master/docs/code_review.md
        - Read and follow the contribution guide when reviewing: https://github.com/dimagi/commcare-hq/blob/master/CONTRIBUTING.rst
        - Read and follow the project standards and best practices guide: https://github.com/dimagi/commcare-hq/blob/master/STANDARDS.rst.
    path_instructions:
        - path: "**/*.js"
          instructions: >-
            - Review the JavaScript code against the Google JavaScript style guide by reading this guide: https://google.github.io/styleguide/jsguide.html.
            - Read and follow this guide as well: https://github.com/dimagi/commcare-hq/blob/master/docs/js-guide/code-review.rst.
        - path: "**/*.py"
          instructions: >-
            - Review the code following best practises and standards
    path_filters: ["**/*.js", "**/*.py", "**/*.md", "**/*.rst", "**/*.html"]
    auto_review:
        enabled: false
        auto_incremental_review: false
        drafts: false
