name: Label PR if get_blob_db is used

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created, edited]

jobs:
  label-if-get-blob-db-used:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for full history to do git diff with base

      - name: Get list of files changed in the PR
        id: file_list
        run: |
          FILES=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }}...HEAD)
          echo ${{ github.event.pull_request.base.ref }}
          echo "FILES=$FILES" >> $GITHUB_OUTPUT

      - name: Search for blob-related functions in modified files
        id: grep_check
        run: |
          FILES="${{ steps.file_list.outputs.FILES }}"
          FOUND=false
      
          PATTERN="get_blob_db|get_email_configuration"
  
          for file in $FILES; do
            if [[ -f "$file" ]] && grep -Eq "$PATTERN" "$file"; then
              FOUND=true
              break
            fi
          done

          echo "FOUND=$FOUND" >> $GITHUB_OUTPUT


      - name: Add label to PR if found
        if: steps.grep_check.outputs.FOUND == 'true'
        run: |
          gh pr edit "$PR_URL" --add-label "test on staging"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
